# Liniare Aljebra

In [2]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([7,9,6])

In [3]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
vector

array([7, 9, 6])

In [5]:
matrix+3

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
#++
a=np.array([
    [1,2],
    [3,4]
])
b=np.array([
    [1,2],
    [3,4]
])
print("a+b=/n",a+b)

a+b=/n [[2 4]
 [6 8]]


In [11]:
#**

a=np.array([
    [2,3],[2,3]
])
b=np.array([
    [3,4],[5,6]
])

print("a*b=/n",a*b)

a*b=/n [[ 6 12]
 [10 18]]


In [13]:
#dot*
m1=np.array([
    [1,2,3],[4,5,6]
])
m2=np.array([
    [7,8],[9,10],[11,12]
])
m1.dot(m2)

array([[ 58,  64],
       [139, 154]])

In [14]:
#Transport Matrix
A=np.array([[1,2,0],
          [3,5,9]])
A.T

array([[1, 3],
       [2, 5],
       [0, 9]])

In [15]:
#Negative Matrix
C=np.array([[-5,-3,-1],
          [1,3,5]])
print(C)
print(-C)

[[-5 -3 -1]
 [ 1  3  5]]
[[ 5  3  1]
 [-1 -3 -5]]


In [16]:
#identity Matrix
I=np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Invers Matrix
D=np.array([[6,2],
          [1,2]])
print(np.linalg.inv(D))

[[ 0.2 -0.2]
 [-0.1  0.6]]


In [18]:
#Determinant
a=np.array([[28,18,8],[72,19,38],[81,24,44]])
b=np.linalg.det(a)
print('Determinant:',b)

Determinant: -2235.999999999998


In [19]:
#Eigen Vector & Eigen Values
M=np.array([[1,2,3],[4,5,6],[2,9,5]])
eigvals,eigvecs=np.linalg.eig(M)
print("Eigen Value\n",eigvals)
print("Eigen Vector\n",eigvecs)

Eigen Value
 [13.60405743+0.j         -1.30202872+0.85467427j -1.30202872-0.85467427j]
Eigen Vector
 [[ 0.27290581+0.j          0.48002115+0.29391132j  0.48002115-0.29391132j]
 [ 0.63242049+0.j          0.39363982-0.13316529j  0.39363982+0.13316529j]
 [ 0.72495983+0.j         -0.71450019+0.j         -0.71450019-0.j        ]]
